#!/usr/bin/env node
/**
 * build-seo.mjs — generates the JSON-LD block in index.html.
 *
 * WHY THIS EXISTS
 * ---------------
 * Three separate defects were found in one audit — the FAQPage had drifted so far from
 * the page that ZERO of its ten answers still matched the visible text, the Offer block
 * advertised one plan when two are sold, and AggregateRating was a literal "5" that
 * happened to still be true. They looked like three bugs. They were one: hand-maintained
 * literals in a static file, with nothing to notice when the page moved and they didn't.
 *
 * So this script does not fix those values. It removes the ability to hold them wrong:
 *
 *   FAQPage   is parsed FROM the rendered FAQ markup, so schema and page are the same
 *             strings by construction. Edit the page; the schema follows. There is
 *             deliberately no separate FAQ data file — a second copy is a second thing
 *             to drift.
 *   Offer     is generated from data/site-data.json, the one place prices are written.
 *   Rating    is fetched from Apple at build time. Nobody types it — and if that
 *             fetch fails the build STOPS rather than republishing yesterday's
 *             number, because a stale rating quietly re-asserted is the exact bug
 *             this file exists to prevent. Same rule as the price assertion.
 *
 * And where a literal genuinely has to live in prose (prices appear in sentences), the
 * script ASSERTS the prose agrees with site-data.json and fails the build if it doesn't.
 * Drift becomes a build error instead of a silent lie.
 *
 * Run locally (`node .scripts/build-seo.mjs`) and it rewrites index.html in place; the
 * result is committed so the repo is always accurate. It also runs on every Vercel
 * deploy via buildCommand, which is what keeps the rating current.
 */

import { readFile, writeFile, rm } from 'node:fs/promises';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';

const ROOT = join(dirname(fileURLToPath(import.meta.url)), '..');
const INDEX = join(ROOT, 'index.html');
const DATA = join(ROOT, 'data', 'site-data.json');

const START = '<!-- SEO:JSONLD:START — generated by .scripts/build-seo.mjs. Do not hand-edit. -->';
const END = '<!-- SEO:JSONLD:END -->';

const log = (...a) => console.log('  ', ...a);
const fail = (msg) => { console.error(`\n  BUILD FAILED: ${msg}\n`); process.exit(1); };

/** Decode the handful of entities that appear in this page's copy. */
function decode(s) {
  return s
    .replace(/<[^>]+>/g, '')
    .replace(/&nbsp;/g, ' ').replace(/&amp;/g, '&').replace(/&lt;/g, '<')
    .replace(/&gt;/g, '>').replace(/&quot;/g, '"').replace(/&#39;/g, "'")
    .replace(/&trade;/g, '™').replace(/&mdash;/g, '—').replace(/&rarr;/g, '→')
    .replace(/\s+/g, ' ')
    .trim();
}

/**
 * Pull the visible Q&A pairs straight out of the FAQ markup.
 *
 * The question sits in a <span> inside the button, alongside a decorative arrow glyph
 * that must not end up in the schema — hence the explicit strip of the trailing chevron.
 */
function parseFaq(html) {
  const out = [];
  const re = /<button class="faq-q"[^>]*>([\s\S]*?)<\/button>\s*<div class="faq-a">([\s\S]*?)<\/div>/g;
  let m;
  while ((m = re.exec(html)) !== null) {
    const q = decode(m[1]).replace(/\s*›\s*$/, '').trim();
    const a = decode(m[2]);
    if (q && a) out.push({ q, a });
  }
  return out;
}

/**
 * Apple's public lookup endpoint. No key, no auth, and it is the same record the App
 * Store shows the public — which is the point: the rating on the site is the rating on
 * the store, not a number somebody remembered to update.
 */
async function fetchRating(appStoreId) {
  const ctl = new AbortController();
  const t = setTimeout(() => ctl.abort(), 10_000);
  try {
    const r = await fetch(`https://itunes.apple.com/lookup?id=${appStoreId}&country=us`, { signal: ctl.signal });
    if (!r.ok) throw new Error(`HTTP ${r.status}`);
    const j = await r.json();
    const rec = j?.results?.[0];
    if (!rec) throw new Error('no result in lookup response');
    const value = rec.averageUserRating;
    const count = rec.userRatingCount;
    // A rating of 0 from 0 ratings is legitimate for a new app but must NOT be published:
    // Google rejects an AggregateRating with a zero count, and it reads as "rated 0".
    if (typeof value !== 'number' || typeof count !== 'number' || count < 1) {
      throw new Error(`unusable rating (value=${value}, count=${count})`);
    }
    return { ratingValue: String(Math.round(value * 10) / 10), ratingCount: String(count), live: true };
  } finally {
    clearTimeout(t);
  }
}

/**
 * Every price in site-data must appear in the visible copy, and no OTHER price-looking
 * string may appear that site-data doesn't know about. The second half is the one that
 * catches real drift: a stale "$14.99" left in a sentence after a price change.
 */
function assertPricesAgree(html, plans) {
  const visible = html.slice(html.indexOf(END) + END.length); // schema excluded on purpose
  const known = new Set(plans.map((p) => p.price));
  const found = new Set();
  for (const m of visible.matchAll(/\$(\d+\.\d{2})\b/g)) found.add(m[1]);

  const unknown = [...found].filter((p) => !known.has(p));
  if (unknown.length) {
    fail(`index.html shows price(s) ${unknown.map((p) => '$' + p).join(', ')} that are not in data/site-data.json.\n` +
         `  Either the copy is stale or site-data is. Fix one, then re-run.`);
  }
  const unused = [...known].filter((p) => !found.has(p));
  if (unused.length) log(`note: $${unused.join(', $')} is in site-data but not shown on index.html (fine if that plan isn't marketed here)`);
  log(`prices agree — visible: ${[...found].map((p) => '$' + p).join(', ') || 'none'}`);
}

const main = async () => {
  console.log('\nbuild-seo: generating structured data from a single source\n');

  const data = JSON.parse(await readFile(DATA, 'utf8'));
  let html = await readFile(INDEX, 'utf8');

  if (!html.includes(START) || !html.includes(END)) {
    fail(`index.html is missing the ${START.slice(0, 22)}…/END markers. They delimit the generated block.`);
  }

  // ── FAQ, taken from the page itself ────────────────────────────────────────
  const faq = parseFaq(html);
  if (faq.length < 5) fail(`only ${faq.length} FAQ pairs parsed — the FAQ markup shape probably changed. Refusing to publish a truncated FAQPage.`);
  log(`FAQ: ${faq.length} question/answer pairs read from the visible page`);

  // ── Rating, taken from Apple ───────────────────────────────────────────────
  // NEVER publish a rating we did not just verify. There is deliberately no
  // committed fallback: falling back would republish a stale number, which is
  // indistinguishable to a reader from a fresh one and is precisely the failure
  // this generator was written to end.
  //
  // Default is to FAIL the build — loud, and a human retries. The escape hatch
  // omits the block entirely (still never publishing an unverified number) for
  // the case where a deploy must go out during an Apple outage:
  //     SEO_ALLOW_MISSING_RATING=1 node .scripts/build-seo.mjs
  let rating = null;
  try {
    rating = await fetchRating(data.appStoreId);
    log(`rating: ${rating.ratingValue} from ${rating.ratingCount} ratings (verified live from Apple)`);
  } catch (e) {
    if (process.env.SEO_ALLOW_MISSING_RATING === '1') {
      console.warn(`\n  WARNING: Apple lookup failed (${e.message}).\n` +
                   `  SEO_ALLOW_MISSING_RATING=1 is set, so AggregateRating is being OMITTED from this build.\n` +
                   `  The site will publish no rating until the next successful build.\n`);
    } else {
      fail(`could not verify the App Store rating (${e.message}).\n` +
           `  Refusing to publish a rating this build did not confirm.\n` +
           `  Retry, or deploy without the rating: SEO_ALLOW_MISSING_RATING=1`);
    }
  }

  // ── Prices, asserted against the prose ─────────────────────────────────────
  assertPricesAgree(html, data.plans);

  // ── Offers ─────────────────────────────────────────────────────────────────
  // AggregateOffer because two plans are genuinely purchasable. No trial language: an
  // Offer states unconditional terms, and trial eligibility is Apple's per-Apple-ID
  // decision, so any trial claim here would be unconditional and therefore sometimes false.
  const prices = data.plans.map((p) => Number(p.price)).sort((a, b) => a - b);
  const offers = {
    '@type': 'AggregateOffer',
    priceCurrency: data.plans[0].priceCurrency,
    lowPrice: prices[0].toFixed(2),
    highPrice: prices[prices.length - 1].toFixed(2),
    offerCount: String(data.plans.length),
    url: data.appStoreUrl,
    availability: 'https://schema.org/InStock',
    offers: data.plans.map((p) => ({
      '@type': 'Offer',
      name: p.name,
      price: p.price,
      priceCurrency: p.priceCurrency,
      url: data.appStoreUrl,
      availability: 'https://schema.org/InStock',
      priceSpecification: {
        '@type': 'UnitPriceSpecification',
        price: p.price,
        priceCurrency: p.priceCurrency,
        billingDuration: 1,
        billingIncrement: 1,
        unitCode: 'ANN',
      },
    })),
  };

  // ── The graph ──────────────────────────────────────────────────────────────
  // MobileApplication keeps its hand-written descriptive fields (name, featureList) —
  // those are editorial and don't drift into falsehood the way a price or a rating does.
  const existing = JSON.parse(
    html.slice(html.indexOf(START) + START.length, html.indexOf(END))
      .replace(/^\s*<script type="application\/ld\+json">/, '')
      .replace(/<\/script>\s*$/, '')
  );
  const app = existing['@graph'].find((n) => n['@type'] === 'MobileApplication');
  if (!app) fail('no MobileApplication node found in the existing block — cannot preserve editorial fields.');

  app.offers = offers;
  if (rating) {
    app.aggregateRating = {
      '@type': 'AggregateRating',
      ratingValue: rating.ratingValue,
      ratingCount: rating.ratingCount,
      bestRating: '5',
      worstRating: '1',
    };
  } else {
    // Omitted rather than carried over from the previous build.
    delete app.aggregateRating;
  }

  const graph = [
    app,
    {
      '@type': 'FAQPage',
      mainEntity: faq.map(({ q, a }) => ({
        '@type': 'Question',
        name: q,
        acceptedAnswer: { '@type': 'Answer', text: a },
      })),
    },
  ];

  const block = `${START}\n  <script type="application/ld+json">\n${
    JSON.stringify({ '@context': 'https://schema.org', '@graph': graph }, null, 2)
      .split('\n').map((l) => '  ' + l).join('\n')
  }\n  </script>\n  ${END}`;

  const before = html.indexOf(START);
  const after = html.indexOf(END) + END.length;
  html = html.slice(0, before) + block + html.slice(after);
  await writeFile(INDEX, html);

  log(`wrote ${graph.length} top-level nodes: ${graph.map((n) => n['@type']).join(', ')}`);

  // ── Keep this script out of the deployed output ────────────────────────────
  // outputDirectory is '.', so every source file is also a served file. A dot
  // prefix does NOT protect it — Vercel serves /.scripts/build-seo.mjs happily
  // (verified against a preview deployment). A build script is not a served
  // asset, so remove it from the build workspace once its work is done.
  //
  // Guarded on VERCEL so a local run never deletes the developer's own copy.
  // Node has already loaded this module into memory, so unlinking it mid-run
  // is safe. Vercel builds from a fresh checkout every time, so the repo is
  // untouched — only the output loses it.
  if (process.env.VERCEL === '1') {
    await rm(join(ROOT, '.scripts'), { recursive: true, force: true });
    log('removed .scripts/ from the deployed output');
  }

  console.log('\nbuild-seo: done\n');
};

main().catch((e) => fail(e.stack || String(e)));
